### ISSUE TITLE
Incompatible with Research Pal 1.1

### ISSUE THREAD

**Issue by Gwilt** [FluffierThanThou/ResearchTree#37]
**Describe the bug**  
When both Research Tree and Research Pal are installed there are graphical issues when in the colony screen - tooltips remain on screen and the main menu is unavailable.

See - https://drive.google.com/file/d/1XxJd4eLRE-NFMbLqXzjF7cqazLZ6T9tD/view?usp=sharing

**Expected behavior**  
I wasn't aware that both mods essentially did the same thing

**Steps to reproduce**  
Install Research Tree (with dependencies) and Research Pal

**Other mods**  
As above.

**Output log**  

**Save game**  

**Screenshots**  

https://drive.google.com/file/d/1XxJd4eLRE-NFMbLqXzjF7cqazLZ6T9tD/view?usp=sharing

**Environment**  
 - OS: Windows 10 Pro, 64 Bit
 - 32/64 bits 
 
**Game**
 - 32/64 bits
 - Steam/DRM free
 - Version
Steam, 1.1, Royalty DLC not installed / enabled.

Comment 
It took me about 30 - 45 minutes to troubleshoot the issue. At the time I didn't relaise both mods essentially did the same thing and thus only one of the other would be required. Could you please add a comment / disclaimer to Research Tree indicating that if you have both mods installed at the same time that the user might experience issues.
![Rimworld](https://user-images.githubusercontent.com/53935543/76211555-499ba980-6252-11ea-80e7-beff8ef39be3.png)

**Comment by notfood** [comment]
I should be able to add an "incompatible with" in the About.xml

**Comment by FluffierThanThou** [comment]
same on this side. Granted, this should have been fairly obvious, but
making it explicit can't hurt.

**Comment by ELLIOTTCABLE** [comment]
Hey there; just adding a log, since one wasn't included in the O.P.: launched with only Mod Manager, HugsLib, and ResearchPal/ResearchTree.

https://gist.github.com/ELLIOTTCABLE/51e85aa7aa38b53b8f1eb0fff926f89b

I would like to 👍 for a *fix*, though, if at all possible - with enough mods installed, the two graph-layout algorithms produce substantially different results, and it'd be nice to be able to run the game with *both* of them, allowing someone to decide which layout they prefer for a given <set of mods>.

Obviously, a non-pressing issue; but I thought I'd throw this in there! <3

**Comment by FluffierThanThou** [comment]
I'm afraid this is just not something that has even a remote priority. Both mods implement a research queue system with pretty much the same code, that simply cannot exist together nicely, and it's not really worth the effort to try and make them.

You're just gonna have to try the two algorithms one by one, sorry ;)
